# Generated by Django 3.2.16 on 2023-01-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='overall_comment',
            field=models.CharField(choices=[(0, 'Display'), (1, 'Hide')], default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='personal_comment',
            field=models.CharField(choices=[(0, 'Display'), (1, 'Hide')], default=0, max_length=200),
        ),
    ]
