# Generated by Django 3.2.16 on 2023-01-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0002_auto_20230119_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_reference',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.RemoveField(
            model_name='task',
            name='booking_reference',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
