# Generated by Django 3.2.16 on 2023-01-26 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ben_ken', '0003_auto_20230126_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11)),
                ('address_line_1', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_reference', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('week_booking', models.SmallIntegerField()),
                ('year_booking', models.SmallIntegerField()),
                ('calendar_reference', models.SmallIntegerField(unique=True)),
                ('number_of_o18', models.SmallIntegerField()),
                ('number_of_u18', models.SmallIntegerField()),
                ('number_of_pets', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
