# Generated by Django 3.2.16 on 2023-01-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ben_ken', '0004_booking_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='calendar_reference',
        ),
        migrations.AddField(
            model_name='booking',
            name='if_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('overall_comment', models.CharField(max_length=250)),
                ('personal_comment', models.CharField(max_length=250)),
                ('overall_feeling', models.CharField(choices=[('Happy', 'Happy'), ('Indifferent', 'Indifferent'), ('Unhappy', 'Unhappy')], max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
