# Generated by Django 3.2.16 on 2023-01-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0005_auto_20230127_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='booking_reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ben_ken.booking'),
            preserve_default=False,
        ),
    ]
