# Generated by Django 3.2.16 on 2023-02-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0013_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_reference',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
