# Generated by Django 3.2.16 on 2023-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0014_auto_20230201_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admin_commnets',
            new_name='admin_comments',
        ),
    ]
