# Generated by Django 3.2.16 on 2023-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0015_rename_admin_commnets_profile_admin_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charge',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
