# Generated by Django 3.2.16 on 2023-02-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0017_booking_additional_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ben_ken.profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_o18',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_pets',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_u18',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
