# Generated by Django 3.2.16 on 2023-02-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ben_ken', '0019_booking_provided_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_o18',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_pets',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_u18',
            field=models.SmallIntegerField(default=0),
        ),
    ]
