# Generated by Django 3.2.16 on 2023-02-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0020_auto_20230208_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallComment',
            fields=[
                ('o_comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('overall_comment', models.CharField(max_length=250)),
                ('overall_feeling', models.CharField(choices=[('Happy', 'Happy'), ('Indifferent', 'Indifferent'), ('Unhappy', 'Unhappy')], max_length=11)),
                ('booking_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ben_ken.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalComment',
            fields=[
                ('p_comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('personal_comment', models.CharField(max_length=250)),
                ('overall_feeling', models.CharField(choices=[('Happy', 'Happy'), ('Indifferent', 'Indifferent'), ('Unhappy', 'Unhappy')], max_length=11)),
                ('booking_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ben_ken.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
