# Generated by Django 3.2.16 on 2023-02-14 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0021_auto_20230213_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overallcomment',
            name='booking_reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ben_ken.booking'),
        ),
    ]
