# Generated by Django 3.2.16 on 2023-02-15 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ben_ken', '0023_alter_overallcomment_overall_feeling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overallcomment',
            old_name='overall_comment',
            new_name='comment',
        ),
    ]
